# -*- coding: utf-8 -*-
"""video_2_speech.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/158GgzuqsMr7XRQPnPZhhTmiRdmVtmjCY
"""

!pip install SpeechRecognition moviepy

"""### Mount dirve folders into colab environment"""

from google.colab import drive
drive.mount('/content/drive')

import speech_recognition as sr 
import moviepy.editor as mp
import sys

out_file_name = input("Enter output file name ...")
video_file_path =  input("Enter the path to the video file ...")

"""### Convert the video to an audio file """

clip = mp.VideoFileClip(video_file_path) 
if clip.duration > 600 : # 600s max video duraiton to process
  print("ERROR : cannot process a video with more than 10 mins length !")
  sys.exit()
audio_file_name = "converted.tmp.wav"
clip.audio.write_audiofile(audio_file_name)

r = sr.Recognizer()

audio = sr.AudioFile(audio_file_name)

with audio as source:
  audio_file = r.record(source)
result = r.recognize_google(audio_file)

"""### Writing the result in a file"""

with open(out_file_name, mode ='w') as file:  
   file.write(result)

"""### Rermove stepwords from the result"""

import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

text_tokens = word_tokenize(result)

tokens_without_sw = [word for word in text_tokens if not word in stopwords.words()]

tokens_without_sw